"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "es" | "en" | "fr" | "de" | "pt";
type Currency = "EUR" | "USD" | "GBP";
type Region = "ES" | "US" | "UK" | "FR" | "DE";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  currency: Currency;
  setCurrency: (curr: Currency) => void;
  region: Region;
  setRegion: (reg: Region) => void;
  t: (key: string) => string;
  formatPrice: (price: number) => string;
}

const translations = {
  es: {
    "nav.start": "Inicio",
    "nav.catalog": "Catálogo",
    "nav.cart": "Favoritos",
    "hero.title": "Ofertas Exclusivas de",
    "hero.subtitle": "Descubre los mejores productos de Hacoo con hasta un 90% de descuento. Calidad verificada por nuestra comunidad.",
    "hero.cta": "Explorar Catálogo",
    "hero.telegram": "Unirse al Telegram",
    "catalog.title": "Catálogo",
    "catalog.subtitle": "Explora nuestra selección curada de los mejores productos. Filtra para encontrar lo que buscas.",
    "catalog.search": "Buscar por nombre, marca o categoría...",
    "catalog.filters": "Filtros",
    "catalog.categories": "Categorías",
    "catalog.brands": "Marcas",
    "catalog.all": "Todos",
    "catalog.allBrands": "Todas",
    "catalog.showing": "Mostrando",
    "catalog.products": "productos",
    "catalog.clear": "Limpiar filtros",
    "catalog.empty": "No se encontraron productos",
    "catalog.empty_desc": "Intenta ajustar tus filtros o buscar términos más generales.",
    "cart.title": "Favoritos",
    "cart.empty": "Tu lista está vacía",
    "nav.profile": "Perfil",
    "nav.login": "Entrar",
    "nav.telegram": "Telegram",
    "product.exclusive": "Exclusivo",
    "product.add_to_cart": "Añadir a la cesta",
    "product.login_to_add": "Inicia sesión para añadir",
    "product.ultra_price": "Precio Ultra",
    "footer.updates": "Actualizaciones & Alertas",
    "footer.desc": "La plataforma definitiva para encontrar los mejores productos de Hacoo con descuentos imbatibles.",
    "footer.explore": "Explorar",
    "footer.legal": "Legal",
    "footer.community": "Comunidad",
    "settings.success": "Perfil actualizado correctamente",
    "settings.error": "Error al actualizar",
    "settings.reset_sent": "Enlace de restablecimiento enviado",
    "push.title": "¡No te pierdas ninguna oferta!",
    "push.desc": "Activa las notificaciones para recibir alertas exclusivas y cupones como el código ULTRA14 directamente en tu dispositivo.",
    "push.subscribed": "Suscrito correctamente",
    "push.activate": "Activar Alertas",
    "push.later": "Más tarde",
    "header.shopping": "Premium Shopping",
    "header.system_pref": "Preferencia de Sistema",
    "header.regional_lang": "Idioma Regional",
    "header.more_settings": "Más Ajustes",
    "header.my_account": "Mi Cuenta",
    "header.logout": "Cerrar sesión",
    "header.login": "Acceso",
    "header.admin_panel": "Panel de Control",
    "promo.reward": "Recompensa",
    "promo.valid": "Válido por 24h",
    "promo.desc": "Aprovecha un 14% EXTRA de descuento usando nuestro código VIP.",
    "promo.copy": "COPIAR CUPÓN",
    "promo.copied": "¡CÓDIGO COPIADO!",
    "home.why_choose": "¿Por qué elegir Hacoo Ultra?",
    "home.why_choose_desc": "Filtramos miles de productos para traerte solo lo mejor al mejor precio, ahorrándote tiempo y dinero en cada compra.",
    "home.daily_update": "Actualización diaria",
    "home.daily_update_desc": "Más de 100 enlaces nuevos cada día con las últimas novedades y chollos del mercado.",
    "home.verified_quality": "Calidad Verificada",
    "home.verified_quality_desc": "Solo compartimos productos con excelentes reseñas y vendedores de máxima confianza comprobada.",
    "home.telegram_comm": "Comunidad Telegram",
    "home.telegram_comm_desc": "Acceso exclusivo a ofertas flash que desaparecen en minutos. ¡Únete a más de 5,000 miembros!",
    "home.new_arrivals": "Novedades de la semana",
    "home.new_arrivals_desc": "Los productos más top que acabamos de añadir al catálogo.",
    "home.view_catalog": "Ver catálogo completo",
    "home.cta_title": "¿No quieres perderte ninguna oferta?",
    "home.cta_desc": "Únete a nuestra comunidad en Telegram y recibe links directos cada día en tu móvil. ¡Es gratis y solo enviamos calidad!",
    "home.cta_telegram": "Unirme al Telegram",
    "home.cta_explore": "Explorar Catálogo",
    "profile.panel": "PANEL DE CONTROL",
    "profile.info": "Información Personal",
    "profile.name": "Nombre Público",
    "profile.save": "GUARDANDO...",
    "profile.update": "ACTUALIZAR PERFIL",
    "profile.change_email": "Cambiar Correo Electrónico",
    "profile.new_email": "Nuevo Email",
    "profile.processing": "PROCESANDO...",
    "profile.request_change": "SOLICITAR CAMBIO",
    "profile.email_notice": "Deberás confirmar el cambio en el enlace que enviaremos a tu correo actual y al nuevo para que sea efectivo por seguridad.",
    "profile.security": "Seguridad",
    "profile.reset_password": "Resetear contraseña",
    "profile.session": "Sesión",
    "profile.logout": "Cerrar sesión actual",
    "profile.favorites": "Mis Favoritos",
    "profile.no_favorites": "No tienes favoritos aún",
    "profile.go_shop": "Ir a la tienda",
    "profile.lang_pref": "Preferencia de Idioma",
    "profile.region": "Región de Compra",
    "profile.danger": "Zona Peligrosa",
    "profile.delete_desc": "Eliminar tu cuenta es una acción irreversible. Perderás todos tus favoritos y configuraciones de forma permanente.",
    "profile.delete": "ELIMINAR MI CUENTA DEFINITIVAMENTE",
    "profile.settings": "Ajustes",
  },
  en: {
    "nav.start": "Home",
    "nav.catalog": "Catalog",
    "nav.cart": "Favorites",
    "hero.title": "Exclusive Deals from",
    "hero.subtitle": "Discover the best Hacoo products with up to 90% discount. Quality verified by our community.",
    "hero.cta": "Explore Catalog",
    "hero.telegram": "Join Telegram",
    "catalog.title": "Catalog",
    "catalog.subtitle": "Explore our curated selection of the best products. Filter to find what you're looking for.",
    "catalog.search": "Search by name, brand or category...",
    "catalog.filters": "Filters",
    "catalog.categories": "Categories",
    "catalog.brands": "Brands",
    "catalog.all": "All",
    "catalog.allBrands": "All Brands",
    "catalog.showing": "Showing",
    "catalog.products": "products",
    "catalog.clear": "Clear filters",
    "catalog.empty": "No products found",
    "catalog.empty_desc": "Try adjusting your filters or searching for more general terms.",
    "cart.title": "Favorites",
    "cart.empty": "Your list is empty",
    "nav.profile": "Profile",
    "nav.login": "Login",
    "nav.telegram": "Telegram",
    "product.exclusive": "Exclusive",
    "product.add_to_cart": "Add to Cart",
    "product.login_to_add": "Login to add",
    "product.ultra_price": "Ultra Price",
    "footer.updates": "Updates & Alerts",
    "footer.desc": "The ultimate platform to find the best Hacoo products with unbeatable discounts.",
    "footer.explore": "Explore",
    "footer.legal": "Legal",
    "footer.community": "Community",
    "settings.success": "Profile updated successfully",
    "settings.error": "Error updating profile",
    "settings.reset_sent": "Reset link sent",
    "push.title": "Don't miss any offers!",
    "push.desc": "Enable notifications to receive exclusive alerts and coupons like the ULTRA14 code directly on your device.",
    "push.subscribed": "Subscribed successfully",
    "push.activate": "Enable Alerts",
    "push.later": "Later",
    "header.shopping": "Premium Shopping",
    "header.system_pref": "System Preference",
    "header.regional_lang": "Regional Language",
    "header.more_settings": "More Settings",
    "header.my_account": "My Account",
    "header.logout": "Logout",
    "header.login": "Login",
    "header.admin_panel": "Admin Panel",
    "promo.reward": "Reward",
    "promo.valid": "Valid for 24h",
    "promo.desc": "Take an EXTRA 14% discount using our VIP code.",
    "promo.copy": "COPY COUPON",
    "promo.copied": "CODE COPIED!",
    "home.why_choose": "Why choose Hacoo Ultra?",
    "home.why_choose_desc": "We filter thousands of products to bring you only the best at the best price, saving you time and money on every purchase.",
    "home.daily_update": "Daily Update",
    "home.daily_update_desc": "More than 100 new links every day with the latest news and bargains in the market.",
    "home.verified_quality": "Verified Quality",
    "home.verified_quality_desc": "We only share products with excellent reviews and top-trusted sellers.",
    "home.telegram_comm": "Telegram Community",
    "home.telegram_comm_desc": "Exclusive access to flash deals that disappear in minutes. Join more than 5,000 members!",
    "home.new_arrivals": "Weekly Arrivals",
    "home.new_arrivals_desc": "The hottest products we just added to the catalog.",
    "home.view_catalog": "View Full Catalog",
    "home.cta_title": "Don't want to miss any deals?",
    "home.cta_desc": "Join our Telegram community and receive direct links every day on your mobile. It's free and we only send quality!",
    "home.cta_telegram": "Join Telegram",
    "home.cta_explore": "Explore Catalog",
    "profile.panel": "CONTROL PANEL",
    "profile.info": "Personal Information",
    "profile.name": "Public Name",
    "profile.save": "SAVING...",
    "profile.update": "UPDATE PROFILE",
    "profile.change_email": "Change Email Address",
    "profile.new_email": "New Email",
    "profile.processing": "PROCESSING...",
    "profile.request_change": "REQUEST CHANGE",
    "profile.email_notice": "You must confirm the change in the link we will send to your current and new email for it to be effective for security.",
    "profile.security": "Security",
    "profile.reset_password": "Reset password",
    "profile.session": "Session",
    "profile.logout": "Logout current session",
    "profile.favorites": "My Favorites",
    "profile.no_favorites": "You don't have favorites yet",
    "profile.go_shop": "Go to shop",
    "profile.lang_pref": "Language Preference",
    "profile.region": "Shopping Region",
    "profile.danger": "Danger Zone",
    "profile.delete_desc": "Deleting your account is irreversible. You will lose all your favorites and settings permanently.",
    "profile.delete": "DELETE MY ACCOUNT PERMANENTLY",
    "profile.settings": "Settings",
  },
  fr: {
    "nav.start": "Accueil",
    "nav.catalog": "Catalogue",
    "nav.cart": "Favoris",
    "hero.title": "Offres Exclusives de",
    "hero.subtitle": "Découvrez les meilleurs produits Hacoo avec jusqu'à 90% de réduction. Qualité vérifiée par notre communauté.",
    "hero.cta": "Explorer le Catalogue",
    "hero.telegram": "Rejoindre Telegram",
    "catalog.title": "Catalogue",
    "catalog.subtitle": "Explorez notre sélection organisée des meilleurs produits. Filtrez pour trouver ce que vous cherchez.",
    "catalog.search": "Rechercher par nom, marque ou catégorie...",
    "catalog.filters": "Filtres",
    "catalog.categories": "Catégories",
    "catalog.brands": "Marques",
    "catalog.all": "Tous",
    "catalog.allBrands": "Toutes",
    "catalog.showing": "Affichage de",
    "catalog.products": "produits",
    "catalog.clear": "Effacer les filtres",
    "catalog.empty": "Aucun produit trouvé",
    "catalog.empty_desc": "Essayez d'ajuster vos filtres ou de rechercher des termes plus généraux.",
    "cart.title": "Favoris",
    "cart.empty": "Votre liste est vide",
    "nav.profile": "Profil",
    "nav.login": "Accès",
    "nav.telegram": "Telegram",
    "product.exclusive": "Exclusif",
    "product.add_to_cart": "Ajouter au panier",
    "product.login_to_add": "Connectez-vous pour ajouter",
    "product.ultra_price": "Prix Ultra",
    "footer.updates": "Mises à jour & Alertes",
    "footer.desc": "La plateforme ultime pour trouver les meilleurs produits Hacoo avec des remises imbattables.",
    "footer.explore": "Explorer",
    "footer.legal": "Légal",
    "footer.community": "Communauté",
    "settings.success": "Profil mis à jour avec succès",
    "settings.error": "Erreur lors de la mise à jour",
    "settings.reset_sent": "Lien de réinitialisation envoyé",
    "push.title": "Ne manquez aucune offre !",
    "push.desc": "Activez les notifications pour recevoir des alertes exclusives et des coupons comme le code ULTRA14 directement sur votre appareil.",
    "push.subscribed": "Abonné avec succès",
    "push.activate": "Activer les alertes",
    "push.later": "Plus tard",
    "header.shopping": "Premium Shopping",
    "header.system_pref": "Préférence Système",
    "header.regional_lang": "Langue Régionale",
    "header.more_settings": "Plus de Paramètres",
    "header.my_account": "Mon Compte",
    "header.logout": "Déconnexion",
    "header.login": "Accès",
    "header.admin_panel": "Panneau d'Administration",
    "promo.reward": "Récompense",
    "promo.valid": "Valable 24h",
    "promo.desc": "Profitez d'une remise EXTRA de 14% avec notre code VIP.",
    "promo.copy": "COPIER LE COUPON",
    "promo.copied": "CODE COPIÉ !",
    "home.why_choose": "Pourquoi choisir Hacoo Ultra ?",
    "home.why_choose_desc": "Nous filtrons des milliers de produits pour vous apporter le meilleur au meilleur prix, vous faisant gagner du temps et de l'argent.",
    "home.daily_update": "Mise à jour quotidienne",
    "home.daily_update_desc": "Plus de 100 nouveaux liens chaque jour avec les dernières nouvelles du marché.",
    "home.verified_quality": "Qualité vérifiée",
    "home.verified_quality_desc": "Nous ne partageons que des produits avec d'excellentes critiques et des vendeurs de confiance.",
    "home.telegram_comm": "Communauté Telegram",
    "home.telegram_comm_desc": "Accès exclusif aux offres flash qui disparaissent en quelques minutes.",
    "home.new_arrivals": "Nouveautés de la semaine",
    "home.new_arrivals_desc": "Les produits les plus populaires que nous venons d'ajouter.",
    "home.view_catalog": "Voir le catalogue complet",
    "home.cta_title": "Vous ne voulez manquer aucune offre ?",
    "home.cta_desc": "Rejoignez notre communauté sur Telegram et recevez des liens directs chaque jour sur votre mobile.",
    "home.cta_telegram": "Rejoindre Telegram",
    "home.cta_explore": "Explorer le Catalogue",
    "profile.panel": "PANNEAU DE CONTRÔLE",
    "profile.info": "Informations Personnelles",
    "profile.name": "Nom Public",
    "profile.save": "ENREGISTREMENT...",
    "profile.update": "METTRE À JOUR LE PROFIL",
    "profile.change_email": "Modifier l'adresse e-mail",
    "profile.new_email": "Nouvel E-mail",
    "profile.processing": "TRAITEMENT...",
    "profile.request_change": "DEMANDER LE CHANGEMENT",
    "profile.email_notice": "Vous devrez confirmer le changement via le lien envoyé à vos deux adresses e-mail pour des raisons de sécurité.",
    "profile.security": "Sécurité",
    "profile.reset_password": "Réinitialiser le mot de passe",
    "profile.session": "Session",
    "profile.logout": "Déconnexion de la session actuelle",
    "profile.favorites": "Mes Favoris",
    "profile.no_favorites": "Vous n'avez pas encore de favoris",
    "profile.go_shop": "Aller à la boutique",
    "profile.lang_pref": "Préférence de Langue",
    "profile.region": "Région d'Achat",
    "profile.danger": "Zone de Danger",
    "profile.delete_desc": "Supprimer votre compte est irréversible. Vous perdrez tous vos favoris et paramètres définitivement.",
    "profile.delete": "SUPPRIMER DÉFINITIVEMENT MON COMPTE",
    "profile.settings": "Paramètres",
  },
  de: {
    "nav.start": "Startseite",
    "nav.catalog": "Katalog",
    "nav.cart": "Favoriten",
    "hero.title": "Exklusive Angebote von",
    "hero.subtitle": "Entdecken Sie die besten Hacoo-Produkte mit bis zu 90% Rabatt. Qualität von unserer Community geprüft.",
    "hero.cta": "Katalog erkunden",
    "hero.telegram": "Telegram beitreten",
    "catalog.title": "Katalog",
    "catalog.subtitle": "Entdecken Sie unsere kuratierte Auswahl der besten Produkte. Filtern Sie, um das zu finden, was Sie suchen.",
    "catalog.search": "Suche nach Name, Marke oder Kategorie...",
    "catalog.filters": "Filter",
    "catalog.categories": "Kategorien",
    "catalog.brands": "Marken",
    "catalog.all": "Alle",
    "catalog.allBrands": "Alle Marken",
    "catalog.showing": "Anzeige von",
    "catalog.products": "Produkten",
    "catalog.clear": "Filter löschen",
    "catalog.empty": "Keine Produkte gefunden",
    "catalog.empty_desc": "Versuchen Sie, Ihre Filter anzupassen oder nach allgemeineren Begriffen zu suchen.",
    "cart.title": "Favoriten",
    "cart.empty": "Ihre Liste ist leer",
    "nav.profile": "Profil",
    "nav.login": "Anmelden",
    "nav.telegram": "Telegram",
    "product.exclusive": "Exklusiv",
    "product.add_to_cart": "In den Warenkorb",
    "product.login_to_add": "Zum Hinzufügen anmelden",
    "product.ultra_price": "Ultra-Preis",
    "footer.updates": "Updates & Warnungen",
    "footer.desc": "Die ultimative Plattform, um die besten Hacoo-Produkte mit unschlagbaren Rabatten zu finden.",
    "footer.explore": "Erkunden",
    "footer.legal": "Rechtliches",
    "footer.community": "Gemeinschaft",
    "settings.success": "Profil erfolgreich aktualisiert",
    "settings.error": "Fehler beim Aktualisieren",
    "settings.reset_sent": "Reset-Link gesendet",
    "push.title": "Verpassen Sie keine Angebote!",
    "push.desc": "Aktivieren Sie Benachrichtigungen, um exklusive Warnungen und Gutscheine wie den ULTRA14-Code direkt auf Ihr Gerät zu erhalten.",
    "push.subscribed": "Erfolgreich abonniert",
    "push.activate": "Benachrichtigungen aktivieren",
    "push.later": "Später",
    "header.shopping": "Premium Shopping",
    "header.system_pref": "Systemeinstellungen",
    "header.regional_lang": "Regionalsprache",
    "header.more_settings": "Mehr Einstellungen",
    "header.my_account": "Mein Konto",
    "header.logout": "Abmelden",
    "header.login": "Anmelden",
    "header.admin_panel": "Admin-Bereich",
    "promo.reward": "Belohnung",
    "promo.valid": "Gültig für 24h",
    "promo.desc": "Nutzen Sie 14% EXTRA-Rabatt mit unserem VIP-Code.",
    "promo.copy": "GUTSCHEIN KOPIEREN",
    "promo.copied": "CODE KOPIERT!",
    "home.why_choose": "Warum Hacoo Ultra wählen?",
    "home.why_choose_desc": "Wir filtern tausende Produkte, um Ihnen nur das Beste zum besten Preis zu bieten.",
    "home.daily_update": "Tägliches Update",
    "home.daily_update_desc": "Jeden Tag mehr als 100 neue Links mit den neuesten Angeboten.",
    "home.verified_quality": "Geprüfte Qualität",
    "home.verified_quality_desc": "Wir teilen nur Produkte mit exzellenten Bewertungen.",
    "home.telegram_comm": "Telegram-Community",
    "home.telegram_comm_desc": "Exklusiver Zugang zu Flash-Angeboten, die in Minuten verschwinden.",
    "home.new_arrivals": "Neuheiten der Woche",
    "home.new_arrivals_desc": "Die Top-Produkte, die wir gerade hinzugefügt haben.",
    "home.view_catalog": "Vollständigen Katalog ansehen",
    "home.cta_title": "Keine Angebote verpassen?",
    "home.cta_desc": "Treten Sie unserer Telegram-Community bei und erhalten Sie täglich direkte Links.",
    "home.cta_telegram": "Telegram beitreten",
    "home.cta_explore": "Katalog erkunden",
    "profile.panel": "KONTROLLZENTRUM",
    "profile.info": "Persönliche Informationen",
    "profile.name": "Öffentlicher Name",
    "profile.save": "SPEICHERN...",
    "profile.update": "PROFIL AKTUALISIEREN",
    "profile.change_email": "E-Mail-Adresse ändern",
    "profile.new_email": "Neue E-Mail",
    "profile.processing": "VERARBEITUNG...",
    "profile.request_change": "ÄNDERUNG ANFORDERN",
    "profile.email_notice": "Sie müssen die Änderung über den Link bestätigen, den wir an Ihre aktuelle und neue E-Mail-Adresse senden.",
    "profile.security": "Sicherheit",
    "profile.reset_password": "Passwort zurücksetzen",
    "profile.session": "Sitzung",
    "profile.logout": "Aktuelle Sitzung abmelden",
    "profile.favorites": "Meine Favoriten",
    "profile.no_favorites": "Sie haben noch keine Favoriten",
    "profile.go_shop": "Zum Shop gehen",
    "profile.lang_pref": "Sprachpräferenz",
    "profile.region": "Einkaufsregion",
    "profile.danger": "Gefahrenzone",
    "profile.delete_desc": "Das Löschen Ihres Kontos ist unwiderruflich. Sie verlieren alle Ihre Favoriten und Einstellungen dauerhaft.",
    "profile.delete": "MEIN KONTO ENDGÜLTIG LÖSCHEN",
    "profile.settings": "Einstellungen",
  },
  pt: {
    "nav.start": "Início",
    "nav.catalog": "Catálogo",
    "nav.cart": "Favoritos",
    "hero.title": "Ofertas Exclusivas da",
    "hero.subtitle": "Descubra os melhores produtos Hacoo com até 90% de desconto. Qualidade verificada pela nossa comunidade.",
    "hero.cta": "Explorar Catálogo",
    "hero.telegram": "Entrar no Telegram",
    "catalog.title": "Catálogo",
    "catalog.subtitle": "Explore nossa seleção curada dos melhores produtos. Filtre para encontrar o que procura.",
    "catalog.search": "Buscar por nome, marca ou categoria...",
    "catalog.filters": "Filtros",
    "catalog.categories": "Categorias",
    "catalog.brands": "Marcas",
    "catalog.all": "Todos",
    "catalog.allBrands": "Todas as Marcas",
    "catalog.showing": "Mostrando",
    "catalog.products": "produtos",
    "catalog.clear": "Limpar filtros",
    "catalog.empty": "Nenhum produto encontrado",
    "catalog.empty_desc": "Tente ajustar seus filtros ou buscar termos mais gerais.",
    "cart.title": "Favoritos",
    "cart.empty": "Sua lista está vazia",
    "nav.profile": "Perfil",
    "nav.login": "Acesso",
    "nav.telegram": "Telegram",
    "product.exclusive": "Exclusivo",
    "product.add_to_cart": "Adicionar à cesta",
    "product.login_to_add": "Inicie sessão para adicionar",
    "product.ultra_price": "Preço Ultra",
    "footer.updates": "Atualizações & Alertas",
    "footer.desc": "A plataforma definitiva para encontrar os melhores produtos Hacoo com descontos imbatíveis.",
    "footer.explore": "Explorar",
    "footer.legal": "Legal",
    "footer.community": "Comunidade",
    "settings.success": "Perfil atualizado com sucesso",
    "settings.error": "Erro ao atualizar",
    "settings.reset_sent": "Link de redefinição enviado",
    "push.title": "Não perca nenhuma oferta!",
    "push.desc": "Ative as notificações para receber alertas exclusivos e cupons como o código ULTRA14 diretamente no seu dispositivo.",
    "push.subscribed": "Inscrito com sucesso",
    "push.activate": "Ativar Alertas",
    "push.later": "Mais tarde",
    "header.shopping": "Premium Shopping",
    "header.system_pref": "Preferência do Sistema",
    "header.regional_lang": "Idioma Regional",
    "header.more_settings": "Mais Ajustes",
    "header.my_account": "Minha Conta",
    "header.logout": "Sair",
    "header.login": "Acesso",
    "header.admin_panel": "Painel Admin",
    "promo.reward": "Recompensa",
    "promo.valid": "Válido por 24h",
    "promo.desc": "Aproveite 14% EXTRA de desconto usando nosso código VIP.",
    "promo.copy": "COPIAR CUPOM",
    "promo.copied": "CÓDIGO COPIADO!",
    "home.why_choose": "Por que escolher Hacoo Ultra?",
    "home.why_choose_desc": "Filtramos milhares de produtos para trazer apenas o melhor ao melhor preço.",
    "home.daily_update": "Atualização diária",
    "home.daily_update_desc": "Mais de 100 novos links todos os dias com as últimas novidades.",
    "home.verified_quality": "Qualidade Verificada",
    "home.verified_quality_desc": "Apenas produtos com excelentes avaliações.",
    "home.telegram_comm": "Comunidade Telegram",
    "home.telegram_comm_desc": "Acesso exclusivo a ofertas flash que desaparecem em minutos.",
    "home.new_arrivals": "Novidades da semana",
    "home.new_arrivals_desc": "Os produtos mais tops que acabamos de adicionar.",
    "home.view_catalog": "Ver catálogo completo",
    "home.cta_title": "Não quer perder nenhuma oferta?",
    "home.cta_desc": "Entre em nossa comunidade no Telegram e receba links diretos todos os dias.",
    "home.cta_telegram": "Entrar no Telegram",
    "home.cta_explore": "Explorar Catálogo",
    "profile.panel": "PAINEL DE CONTROLE",
    "profile.info": "Informação Pessoal",
    "profile.name": "Nome Público",
    "profile.save": "SALVANDO...",
    "profile.update": "ATUALIZAR PERFIL",
    "profile.change_email": "Alterar E-mail",
    "profile.new_email": "Novo E-mail",
    "profile.processing": "PROCESSANDO...",
    "profile.request_change": "SOLICITAR ALTERAÇÃO",
    "profile.email_notice": "Você deverá confirmar a alteração no link que enviaremos para o seu e-mail atual e o novo por segurança.",
    "profile.security": "Segurança",
    "profile.reset_password": "Redefinir senha",
    "profile.session": "Sessão",
    "profile.logout": "Sair da sessão atual",
    "profile.favorites": "Meus Favoritos",
    "profile.no_favorites": "Você ainda não tem favoritos",
    "profile.go_shop": "Ir para a loja",
    "profile.lang_pref": "Preferência de Idioma",
    "profile.region": "Região de Compra",
    "profile.danger": "Zona de Perigo",
    "profile.delete_desc": "Excluir sua conta é uma acción irreversível. Você perderá todos os seus favoritos e configurações permanentemente.",
    "profile.delete": "EXCLUIR MINHA CONTA DEFINITIVAMENTE",
    "profile.settings": "Ajustes",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ 
  children, 
  initialLang 
}: { 
  children: React.ReactNode;
  initialLang?: Language;
}) {
  const [language, setLanguageState] = useState<Language>(initialLang || "es");
  const [currency, setCurrencyState] = useState<Currency>("EUR");
  const [region, setRegionState] = useState<Region>("ES");

  useEffect(() => {
    const savedCurrency = localStorage.getItem("hacoo-currency") as Currency;
    const savedRegion = localStorage.getItem("hacoo-region") as Region;
    if (savedCurrency) setCurrencyState(savedCurrency);
    if (savedRegion) setRegionState(savedRegion);
    
    if (initialLang) {
      setLanguageState(initialLang);
      localStorage.setItem("hacoo-lang", initialLang);
      document.cookie = `hacoo-lang=${initialLang}; path=/; max-age=31536000`;
    }
  }, [initialLang]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("hacoo-lang", lang);
    document.cookie = `hacoo-lang=${lang}; path=/; max-age=31536000`;
    
    if (typeof window !== "undefined") {
      const pathname = window.location.pathname;
      const segments = pathname.split("/");
      segments[1] = lang;
      window.location.href = segments.join("/");
    }
  };

  const setCurrency = (curr: Currency) => {
    setCurrencyState(curr);
    localStorage.setItem("hacoo-currency", curr);
  };

  const setRegion = (reg: Region) => {
    setRegionState(reg);
    localStorage.setItem("hacoo-region", reg);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations["es"]] || key;
  };

  const formatPrice = (price: number): string => {
    // Conversion factors (simplified for demo)
    let convertedPrice = price;
    if (currency === "USD") convertedPrice = price * 1.08;
    if (currency === "GBP") convertedPrice = price * 0.86;

    const symbols = {
      EUR: "€",
      USD: "$",
      GBP: "£"
    };

    const isAfter = currency === "EUR" || currency === "GBP";
    const symbol = symbols[currency];

    return isAfter 
      ? `${convertedPrice.toFixed(2)}${symbol}` 
      : `${symbol}${convertedPrice.toFixed(2)}`;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      currency, 
      setCurrency, 
      region, 
      setRegion, 
      t,
      formatPrice
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
